# Generated by Django 4.2.4 on 2023-09-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно')], max_length=10, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('lead_time', models.TimeField(default='00:05:00', verbose_name='время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
